name: blindblindtiger
favicon: null
layout_spectrum: 0
typography_spectrum: 0.15879
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffa87d'
    - '#000000'
    - '#ffffff'
    - '#999999'
    - '#434343'
  brandStrength: 0.5625
  lightness: 0.5519449561834335
  saturation: 0.662396987201646
  rhythmicContrast: 0.8973251627758145
purpose: []
