name: blindblindtiger
favicon: null
layout_spectrum: 0.6292572654783726
typography_spectrum: 0.6716595939360559
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.16496441490016878
  lightness: 0.5519449561834335
  saturation: 0.662396987201646
  rhythmicContrast: 0.8973251627758145
purpose: []
